"""empty message

Revision ID: 530d0da2fd86
Revises: 720a7221d9cd
Create Date: 2021-07-02 23:32:18.532748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530d0da2fd86'
down_revision = '720a7221d9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list', 'notes')
    # ### end Alembic commands ###
